--- Renaming st_id TO student_id IN STUDENTS TABLE ---
ALTER TABLE STUDENTS RENAME COLUMN st_id TO student_id;

--- ALTERING the TABLE COLUMNS (CHANGING the LENGTH FROM PREV VALUE TO 30) ---
ALTER TABLE STUDENTS 
	ALTER COLUMN st_last type varchar(30),
	ALTER COLUMN st_name type varchar(30);
  
--- ADD NEW COLUMN TO THE INTERESTS TABLE ---
ALTER TABLE INTERESTS ADD COLUMN interests text[];

--- INSERT VALUES AS ARRAY GROUPED BY STUDENT_ID ---
INSERT INTO INTERESTS (student_id, interests) SELECT student_id, array_agg(interest) FROM interests GROUP BY (student_id);

--- FILTER COLUMNS FROM EMPTY VALUES ---
DELETE FROM INTERESTS WHERE interests.interests is null;

--- REMOVE INTEREST COLUMNS FORM INTERESTS TABLE ---
ALTER TABLE INTERESTS DROP COLUMN interest;